### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/jupyter.radiasoft.org#1]
This issue will be used for general announcements regarding the Jupyter server
   https://jupyter.radiasoft.org 

All known users will be referenced below, so that they are notified of such announcements via standard GitHub mechanisms.

Please use the issues feature of this GitHub repository to report bugs and to request assistance or new features.

Usage of the server is increasing. If you the server seems slow, please execute the 'uptime' command:
   jupyter$ uptime
If the load average exceeds 16 or if response time is uncharacteristically slow, then please notify us by creating a GitHub issue.

Going forward, all user files are stored in scratch space. This disk is raid protected but is not backed up.

All users must accept responsibility for backing up your own files.

Thanks and happy computing!

@badeirak
@kruisard
@remilehe
@samoylv
@srio
@buzmakov
@robnagler 
@davidsagan
@cfgrote
@al6kar
@fahimhabib
@tonypan-me
@egstern
@angelrf86
@pcj
@spso
@cekees
@prebys
@bruhwile
@xenon4
@ypap
@jseldred
@cemitch
@holzman
@koch253
@mrakitin
@hsinilu
@cchall
@hemenhosseini
@radhakantadash
@ak782
@sszustkowski
@clarkse
@stancari
@elventear 
@aamphy
@ncook882

**Comment by robnagler** [comment]
A new image is available that includes [rslinac](https://github.com/radiasoft/rslinac) and [xraylib](https://github.com/tschoonj/xraylib).

[rsbeams](https://github.com/radiasoft/rsbeams), [rswarp](https://github.com/radiasoft/rswarp), and [rssynergia](https://github.com/radiasoft/rssynergia) are built in the docker image so startup is faster.

If you have problems, please [create an issue](https://github.com/radiasoft/jupyter.radiasoft.org/issues/new). Thanks.

**Comment by robnagler** [comment]
Also, now you can import warp into a notebook without fixing up `sys.argv`.

**Comment by robnagler** [comment]
jupyter.radiasoft.org is down due to disk issues. To monitor progress, subscribe to issue #3.

**Comment by robnagler** [comment]
New container installed with latest Synergia. @ncook882 @cchall

**Comment by robnagler** [comment]
New container installed with [OPAL](https://gitlab.psi.ch/OPAL/src/wikis/home).

@cchall would you check it out? Thanks.

**Comment by robnagler** [comment]
We have upgraded to Jupyter 5.0. If you notice any problems, please let me know.

**Comment by robnagler** [comment]
Had to restart the server. See #13 for the reasons why. There was definitely one long running job that was killed. Sorry about that.

**Comment by bruhwiler** [comment]
RadiaSoft has created a GitHub repository for easy access to the official suite of `elegant` example files, https://github.com/radiasoft/rselegant/wiki

Users can clone the repository from the Jupyter server and start running `elegant` examples within a couple of minutes.

**Comment by robnagler** [comment]
Please remove old simulations and extraneous large files from jupyter.radiasoft.org by 2/9/2018. 

We will be migrating jupyter.radiasoft.org this weekend, and it will help us speed the process to not have to copy so much data. Thanks!

**Comment by cemitch** [comment]
Should be empty now.

- Chad M.

**Comment by robnagler** [comment]
Today we will be migrating jupyter.radiasoft.org to a new server. If you are running jobs, they'll be stopped, and the data will be copied in that state in the new server.

I apologize for the short notice.

Over the weekend, we'll be upgrading the server with more memory so it will be down some of the time, too.

**Comment by robnagler** [comment]
The server has been migrated. If you find problems, please create a new issue:

https://github.com/radiasoft/jupyter.radiasoft.org/issues/new

**Comment by robnagler** [comment]
[Radia](http://www.esrf.eu/Accelerators/Groups/InsertionDevices/Software/Radia/Documentation/Introduction) is now available. You'll need to restart your servers to get access to it.

For the full list of supported codes, see https://github.com/radiasoft/container-beamsim.

**Comment by robnagler** [comment]
Server upgrade 11/19/2018 23:00 UTC (2p MST). This will involve a reboot and a downtime of about 10 minutes.

**Comment by robnagler** [comment]
We will be moving the server tomorrow before 9a ET. Downtime should be minimal (maybe about 10 minutes).

This involves a new Docker execution module that we developed for better resource control. The change should be transparent from a software point of view. Your servers will be stopped. All your files will be preserved.

There will be resource restrictions. Servers will be limited to 8 cores and 8GB of RAM. If you find this too restrictive, please email support@radiasoft.net, and we may be able to give you more resources.

**Comment by robnagler** [comment]
Migration is complete. The max memory per container is now 16GB.

Also, if there are too many users, servers will be stopped (FIFO) to give new users preference. You are guaranteed a minimum of four hours before new users get priority. If your browser shows a 429, it means the server has too many users.

**Comment by robnagler** [comment]
If you would like to receive updates about RadiaSoft's Public JupyterHub, __[watch this repository](https://help.github.com/en/articles/watching-and-unwatching-repositories). Keeping track in a single issue is not practicle.
