### ISSUE TITLE
Still trying to get loss diagnostics to run

### ISSUE THREAD

**Issue by prebys** [radiasoft/jupyter.radiasoft.org#10]
When I try to add the loss diagnostics to my full analysis job, it causes the kernel to crash with no error message.  

The attached file runs fine with opts.loss_diagnostics set to False, the crashes with it set to True.

[iota-workflow.zip](https://github.com/radiasoft/jupyter.radiasoft.org/files/1020266/iota-workflow.zip)

**Comment by robnagler** [comment]
This is a bit beyond my knowledge. I see this error:

```text
Number of particles: 50000, momentum: 0.0685390832816 GeV/c
Propagator: starting turn 1
bucket index has not been assigned yet
```

I searched and found set_bucket_index in bunch.cc and guessed that I could do this:

```python
    myBunch = read_bunch.read_bunch(opts.start_bunch_file, opts.reference_particle, opts.real_particles, bucket_length, commxx)
    myBunch.set_bucket_index(0)
```

The output looks ok:

```
Read  50000  particles
Using updated bunch constructor
Number of particles: 50000, momentum: 0.0685390832816 GeV/c
Propagator: starting turn 1
Propagator: turn  1/20, macroparticles = 50000, time = 3.10s
Propagator: turn  2/20, macroparticles = 50000, time = 2.97s
Propagator: turn  3/20, macroparticles = 50000, time = 2.88s
Propagator: turn  4/20, macroparticles = 50000, time = 2.91s
[...snip...]
Calculating invariants for file 0
Calculating invariants for file 10
Calculating invariants for file 20
The mean standard deviation in I for individual particles is 67.173549098
```

The std deviation for loss_tracking=False is 66.2148285452 so seems like it worked.

**Comment by bruhwiler** [comment]
@prebys  --  is this issue still important to you?
