### ISSUE TITLE
Parallel-processing Underperforming

### ISSUE THREAD

**Issue by jseldred** [radiasoft/jupyter.radiasoft.org#11]
Usually I run my Synergia scripts with
mpiexec -n 16 synergia script.py
And find it takes about 2-6 seconds per revolution. This evening the same command appears to take 300-500 seconds per revolution. I don't believe I made any significant changes to the scripts themselves.

Running "-n 4", "-n 2", or "-n 1" appears to take 20 seconds per revolution. And running two similar scripts simultaneously with "n-1" appears to take 30 seconds per revolution each.

Is there something wrong with the system or is there just an untypically high user load? I've not encountered this situation in my past experiences with this system. I've attached the screenshot of what my 'top' command says, but I'm not sure how to interpret it.

![top](https://user-images.githubusercontent.com/24280017/27362309-17963220-55f3-11e7-979a-b5d8f12f4e7e.png)

**Comment by robnagler** [comment]
Hi Jeff, it seems there are 4 mpiexec runs going on in your container. You can check by starting a terminal and running:

```sh
ps ax | grep mpiexec
```

If you need help killing some, please let me know.

**Comment by jseldred** [comment]
That seems to have solved the problem, I must have lost track of some terminal windows.

Thank you for your time.
