### ISSUE TITLE
Your server is starting up...

### ISSUE THREAD

**Issue by roberthipple** [radiasoft/jupyter.radiasoft.org#111]
Since Saturday morning I receive the message
Your server is starting up.

You will be redirected automatically when it's ready for you.

No matter what I try, I can't get past this error message

**Comment by robnagler** [comment]
@roberthipple please try again.

**Comment by roberthipple** [comment]
Thank you for working on this - here is the result


Your server is starting up.

You will be redirected automatically when it's ready for you.
100% Complete

Spawn failed: Server at http://10.1.2.32:7920/user/roberthipple/ didn't respond in 45 seconds
Event log
Server requested
Spawning server...
Spawn failed: Server at http://10.1.2.32:7920/user/roberthipple/ didn't respond in 45 seconds

**Comment by robnagler** [comment]
@roberthipple I made another change. Please let me know if it starts now. Sorry for the problems.

**Comment by roberthipple** [comment]
It seems to be working now. Thank you! Is there anything that I may have done to cause this problem?

**Comment by robnagler** [comment]
Nothing you did. Thank you for reporting the error!

There was a confluence of issues including a node whose disk needed to be reformatted.
