### ISSUE TITLE
Removing py2 and jupyter virtual environments

### ISSUE THREAD

**Issue by robnagler** [radiasoft/jupyter.radiasoft.org#112]
We have been operating with py3 as the default virtual environment for some time. The py2 virtual environment has not had much installed in it so we're going to remove it.

The jupyter virtual environment is problematic, because certain calls from notebooks, e.g. os.system, are executed in this environment, which is not complete, and so doesn't work. This can be worked around, but it'll be easier if py3 is the only virtual environment (by default) in Jupyter.

This change will happen in the coming week or so, depending on testing. If you have a great need for py2, we can show you how to set it up. Just create an issue here.

**Comment by robnagler** [comment]
This is on alpha. @cchall would you checkout alpha to see if there are any issues with py3 notebooks. the juptyer venv is gone.

**Comment by cchall** [comment]
@robnagler I tried a few tests notebooks including some with subprocess /  shell execution and there were no problems. 

Minor issue appears during import  of matplotlib  from some rcparam files we apparently have:

> In /home/vagrant/.config/matplotlib/stylelib/rs_many_paper.mplstyle: 
> The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/vagrant/.config/matplotlib/stylelib/rs_many_present.mplstyle: 
> The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/vagrant/.config/matplotlib/stylelib/rs_paper.mplstyle: 
> The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/vagrant/.config/matplotlib/stylelib/rs_present.mplstyle: 
> The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

**Comment by robnagler** [comment]
Great, thanks. I removed jpeg_quality in https://github.com/radiasoft/rsbeams/issues/26

**Comment by robnagler** [comment]
This is now on production
