### ISSUE TITLE
update radia build

### ISSUE THREAD

**Issue by cchall** [radiasoft/jupyter.radiasoft.org#113]
There is an update to Radia (https://github.com/ochubar/Radia/commit/92adc7ab95376243fb7e82c9e083a8a87ec8abb9) that I need to test as a fix to the issues I was observing with dumping during parallel execution.

**Comment by robnagler** [comment]
This is on beta jupyter. If it works, i'll move it to prod tomorrow.

**Comment by cchall** [comment]
@robnagler  Looks like this fixed the issue so it should be good to move to prod whenever you have a chance.

**Comment by robnagler** [comment]
This is on prod.
