### ISSUE TITLE
Update Radia

### ISSUE THREAD

**Issue by cchall** [radiasoft/jupyter.radiasoft.org#124]
There is an update to Radia to add mpi4py functionality that I would like to test (https://github.com/ochubar/Radia/commit/47bd475d6c3dc529fc4e70449855d1ff2cd1b699)

**Comment by robnagler** [comment]
I'm in the midst of upgrading to Fedora 32. I hope to be done "soon". What's your time frame?

**Comment by cchall** [comment]
It's not really urgent. I'd like to try it out by the end of next week if possible, but I don't think it's a problem if it doesn't happen until after the new year.

**Comment by robnagler** [comment]
This is on alpha (sirepo which includes jupyter now). It'll get migrated to production next Monday.

**Comment by cchall** [comment]
Ran some tests with new Radia version using ipyparallel and it appears to be working so far.

**Comment by robnagler** [comment]
Great. It will be on production on Monday, including NERSC.

**Comment by robnagler** [comment]
On prod
