### ISSUE TITLE
parallel Genesis crashing

### ISSUE THREAD

**Issue by cchall** [radiasoft/jupyter.radiasoft.org#126]
Running Genesis as part of an optimization job I keep seeing some evaluation fails while Genesis is running with an error like. I can't recall ever seeing this in the past but this might be the first time I've had many Genesis instances running simultaneously through rsmpi.:

```
At line 795 of file /home/vagrant/src/radiasoft/codes/genesis-20210105.185546/Genesis-1.3-Version2/output.f (unit = 43, file = 'gen.out.dpa.slice000144')
Fortran runtime error: Write exceeds length of DIRECT access record

Error termination. Backtrace:
#0  0x7f6dbe1e7e2a
#1  0x7f6dbe1e8939
#2  0x7f6dbe1e95ff
#3  0x7f6dbe42c79d
#4  0x41f0e4
#5  0x4025a3
#6  0x7f6dbde76081
#7  0x40265d
#8  0xffffffffffffffff
```

**Comment by cchall** [comment]
Just tried re-running the input files for once instance of this and it appears to be repeatable when using genesis_mpi.

When run with serial genesis the simulation completes without error but there are a lot of warning about particle loss so this could be an issue with the initial conditions provided to the simulation causing trouble when run in parallel.

**Comment by robnagler** [comment]
That code is special for mpi. It doesn't open a special file if not mpi. [See line 785](https://github.com/slaclab/Genesis-1.3-Version2/blame/5e93c5f4ab21e3e96daf2ce2a34d25e337c0eaf3/output.f#L785):

```fortran
          if (mpi_size.gt.1) then  ! creata temporary files
            ndmp2tmp=ndmp2
            ndmp2=ndmp2+30
            open(ndmp2,file=outputfile(1:strlen(outputfile))
     +                  //'.dpa'//file_id,
     +        status='unknown',access='direct',
     +        recl=npart*8,err=100)
            j=1
          endif
```

I don't know if the `recl` calculation is correct (probably isn't) so [people are recommending not including it](community.intel.com/t5/Intel-Fortran-Compiler/recl-value-exceeds-the-maximum-allowed-for-the-file-s-record/m-p/1136398#M135852) and [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=37129#c1).

**Comment by cchall** [comment]
This was never resolved.
It hasn't come up again since this incident so it should be closed for now.
