### ISSUE TITLE
Synergia Command Not Found

### ISSUE THREAD

**Issue by jseldred** [radiasoft/jupyter.radiasoft.org#14]
After the most recent server restart, I encounter the following error when trying to run the 'synergia' command:

pyenv: synergia: command not found
The `synergia' command exists in these Python versions:
2.7.12/envs/py2
py2

Can you direct me to the correct way to solve this problem?

Thank you for your time.

**Comment by robnagler** [comment]
As a workaround please enter this command in the terminal:

```sh
pyenv activate py2
```

We'

**Comment by jseldred** [comment]
This fixed the problem. Thank you very much.

I also had to restart my server before entering this command.

**Comment by robnagler** [comment]
@jseldred The problem should be fixed. You might want to restart your server when you get a chance. This will clear up some networking issues.

The reason the python environment wasn't right was that outbound network connections were being blocked (lost, actually). This prevented some python environment fix up code from running.
