### ISSUE TITLE
all text becomes underlined in terminal window after using emacs

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/jupyter.radiasoft.org#15]
OS:  Windows 10
Browser:  latest version of Chrome

If you edit a file with emacs in the terminal window, the text you are editing looks terrible with all kinds of unnecessary and formatting.

Even worse, after exiting emacs, all subsequent text is underlined, as shown in this screenshot:

![image](https://user-images.githubusercontent.com/3825435/32810847-1730cf7c-c95a-11e7-8a2b-751f13a36ab8.png)

**Comment by bruhwiler** [comment]
After about 5 minutes, the unwanted underlining is no longer applied to new text.

Strange.  I'll leave this issue open for a while, in case someone has helpful info.

**Comment by bnash** [comment]
I see the same thing.  Is there another text editor that is recommended?

**Comment by robnagler** [comment]
`export XTERM=ansi` will avoid the underlining issue.

I'll post something to @jupyter/terminado.

**Comment by bnash** [comment]
Thanks Rob.  I tried it, but it didn't resolve the issue.  I still get underlined text.

**Comment by robnagler** [comment]
Typo in workaround. Try: `export TERM=ansi`.  If you want, you can just restart your server: Control Panel > Stop My Server > My Server.

See jupyter/terminado#51 for upstream bug report.

**Comment by robnagler** [comment]
I need to be clear: I added a fix de75bc0237dcd3a593c1c6ac185b5bfb78a50d0a that works around this issue by setting `TERM=ansi` when the terminal starts.

**Comment by bnash** [comment]
I restarted the server and now the problem went away.  Thanks!

**Comment by robnagler** [comment]
BTW, this is still broken in the latest JupyterLab. The TERM=ansi is a workaround but suboptimal.
