### ISSUE TITLE
Saving jupyter notebook as python file fails

### ISSUE THREAD

**Issue by bnash** [radiasoft/jupyter.radiasoft.org#17]
I'm doing a calculation on jupyter.radiasoft.org, and I went to save my notebook as a pure python file and got an error.  Screenshot of error message attached.  Saving as ipython notebook works fine, though.
![screenshot-2017-12-9 jupyter notebook](https://user-images.githubusercontent.com/1112276/33790653-3bca3a06-dc3f-11e7-8991-da300c5a6f92.png)

**Comment by robnagler** [comment]
Is there an indentation issue with one of the Python cells?  Can you execute the cells to verify they are properly formatted Python?

**Comment by bnash** [comment]
Indeed, there was a section that was not properly formatted python.  I had pasted a short piece of code from Igor Pro that I was transforming into correct python.  Commenting it out, the error goes away.
Still, it seems like even bad code should still be transformed into some kind of python like text file?
I'd guess this would be common for people to have some cell that's not correct- maybe just being used as a documentation cell?

**Comment by robnagler** [comment]
Not much I can say about it. You can report issues like this to @jupyter/notebook. I don't know that it's worth your time, though.
