### ISSUE TITLE
errors on login to terminal

### ISSUE THREAD

**Issue by bnash** [radiasoft/jupyter.radiasoft.org#18]
Updating: /home/vagrant/src/biviosoftware/home-env
Can't locate GMP/Mpf.pm in @INC (you may need to install the GMP::Mpf module) (@INC contains: /home/vagrant/src/perl /usr/local/lib6
4/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /ho
me/vagrant/src/perl/Bivio/Type/Number.pm line 6.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/Type/Number.pm line 6.
Compilation failed in require at (eval 16) line 2.
        ...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/Type/Enum.pm line 6.
Compilation failed in require at (eval 15) line 2.
        ...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/DieCode.pm line 5.
Compilation failed in require at /home/vagrant/src/perl/Bivio/Die.pm line 6.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/Die.pm line 6.
Compilation failed in require at (eval 11) line 1.
Can't locate GMP/Mpf.pm in @INC (you may need to install the GMP::Mpf module) (@INC contains: /home/vagrant/src/perl /usr/local/lib6
4/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /ho
me/vagrant/src/perl/Bivio/Type/Number.pm line 6.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/Type/Number.pm line 6.
Compilation failed in require at (eval 16) line 2.
        ...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/Type/Enum.pm line 6.
Compilation failed in require at (eval 15) line 2.
        ...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/DieCode.pm line 5.
Compilation failed in require at /home/vagrant/src/perl/Bivio/Die.pm line 6.
BEGIN failed--compilation aborted at /home/vagrant/src/perl/Bivio/Die.pm line 6.
Compilation failed in require at (eval 11) line 1.

**Comment by robnagler** [comment]
Whoops. I didn't think that would happen.Working on a fix.

**Comment by bnash** [comment]
No error message now.

**Comment by moellep** [comment]
I saw this happen again to bnash. I wasn't able to reproduce on a new jupyter instance.

**Comment by robnagler** [comment]
Maybe it was an old container(?).

**Comment by bruhwiler** [comment]
I see this behavior as well.

**Comment by robnagler** [comment]
On the new server or jupyter.radiasoft?

**Comment by bruhwiler** [comment]
The new server doesn't have this problem.

I only see it on jupyter.radiasoft
The problem doesn't seem to affect use of the terminal window -- it's just annoying.

**Comment by robnagler** [comment]
If you stop and start your server, does it happen?

**Comment by bruhwiler** [comment]
No.  Restarting the server solves the problem.

**Comment by robnagler** [comment]
Your server was running for 3 months so that makes sense. Closing again.
