### ISSUE TITLE
Read_bunch, No attribute 'get_rank'

### ISSUE THREAD

**Issue by jseldred** [radiasoft/jupyter.radiasoft.org#22]
I was running my Synergia simulation on the Radiasfoft Juptyerhub environment for the first time since IPAC and I ran into a new error on previously functioning code.

Here's what it spits out when I use 'mpiexec -n 1 synergia IRCS_SC_WB.py' :
```
  File "IRCS_SC_WB.py", line 551, in <module>
    myBunch = read_bunch.read_bunch(particles_file, reference_particle, opts.real_particles, bucket_length, comm)
  File "build/bdist.linux-x86_64/egg/rssynergia/base_diagnostics/read_bunch.py", line 42, in read_bunch
  File "build/bdist.linux-x86_64/egg/rssynergia/base_diagnostics/read_bunch.py", line 187, in read_h5_particles
AttributeError: 'float' object has no attribute 'get_rank'
```

Is there anything that would have changed about the Synergia simulation environment or is there any known remedy to this?

**Comment by bruhwiler** [comment]
@jseldred -- sorry for the unexpected change in the API. We'll try to prevent such surprises in the future. 

Please let us know if you are operational again.

**Comment by jseldred** [comment]
No problem, everything looks operational now.

Thank you for the rapid response!
