### ISSUE TITLE
Synergia:  container needs to be updated with latest version

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/jupyter.radiasoft.org#23]
I'm told by the Synergia development team that an issue associated with solenoid magnets has been resolved and that it is important for JupyterHub users to have access to the latest version.

Therefore, the beamsim container needs to be rebuilt with the latest version of Synergia.

**Comment by robnagler** [comment]
this will take a couple of hours.

**Comment by robnagler** [comment]
You will need to restart your servers.

Versions:
synergia2 b989040331595df9f7b538bcb9f10c7f5c3883ca
chef-libs 33429b78776f679b3e3eac8e8af77f6fce0aab9f

@sdwebb fbpic 0.9.4 installed
