### ISSUE TITLE
FBPIC is incompatible with Numba version 0.42

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/jupyter.radiasoft.org#25]
![image](https://user-images.githubusercontent.com/3825435/52661115-8154e800-2ebe-11e9-86c3-4fa66b8413f7.png)

The following workaround is being used in the meantime:
jupyter$ pyenv activate py2
jupyter$ pip uninstall numba
jupyter$ pip install numba==0.41.0

...then restart the kernel in your Jupyter notebook.

**Comment by robnagler** [comment]
How soon do you need this?

**Comment by bruhwiler** [comment]
It's not urgent. I have a work around.
