### ISSUE TITLE
Cannot download files

### ISSUE THREAD

**Issue by freeben1** [radiasoft/jupyter.radiasoft.org#26]
I cannot download files from any directory using the method of right clicking on the file and selecting "Download". The file download fails with the message, "Failed - Forbidden".

**Comment by robnagler** [comment]
I see what you are seeing. Will debug and get back to you. Thank you for reporting this error.

**Comment by robnagler** [comment]
[Chrome Issue 455987](https://bugs.chromium.org/p/chromium/issues/detail?id=455987) is causing this problem. Firefox works fine. I don't think there's a solution that can be implemented in JupyterLab, unfortunately.

**Comment by robnagler** [comment]
I submitted https://github.com/jupyterlab/jupyterlab/issues/6106

I'll integrate this patch into our build. This will take a day or so.

**Comment by robnagler** [comment]
Another workaround is to `Open in New Browser Tab`. This will download a notebook and other files. Text files will open in the browser, and `Save As` will work.

Unfortunately, I can't integrate the patch for Chrome in our build easily. The versions are locked in such a way that they always install from the public (npm) repos and override our forked (github) repo. 

We'll just have to hope that the Jupyter folks will fix this soon.

**Comment by robnagler** [comment]
@freeben1 I believe this works now in Chrome. Are you able to download again?

**Comment by freeben1** [comment]
Yes, I just successfully downloaded a file in Chrome.  Thanks!
