### ISSUE TITLE
Add environment variable to limit threading with numba

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/jupyter.radiasoft.org#30]
The suggestion from the FBPIC Slack channel is to set

`export OMP_NUM_THREADS=4`

in the bashrc, with the comment that:

> One more comment on threads: From experience, I advice you to set the number of threads to the number of physical cores per socket (or smaller) to get the best performance. If you have more than one socket, it is best to use one MPI process per socket. If you do not want to use MPI, you should play around a bit with the number of threads to see how it affects performance.

I do not run with MPI, since FBPIC has relatively poor scaling, but I did not see much difference between the 4 and 8 thread settings when running a simulation.

**Comment by robnagler** [comment]
This is code specific. We discussed (offline) adding something like `~/jupyter/bashrc` that would get read by `~/.bashrc` (which you can't edit persistently). This would allow you to set this environment variable in your Jupyter server persistently.

I don't think we can do this generally, because sometimes we want OMP_NUM_THREADS=num-cores and other times to other values.

Is the `~/jupyter/bashrc` solution good enough for you?

**Comment by bruhwiler** [comment]
This is good info for me and for students that are using FBPIC on our Jupyter server

**Comment by robnagler** [comment]
In this particular case, I would think it would be better limit the cores in the fbpic library/program. I'm not sure how to do that with Numba/OpenMP. Something like this at the start of the program might work:

```py
os.environ.setdefault('OMP_NUM_THREADS', '4')
```

When we discussed (offline) about not setting environment variables, it was in the context of wanting to control based upon the execution environment. `setdefault` allows an override from the execution environment. I think if the code doesn't scale, it shouldn't be allowed to consume more resources.

Still, I can implement the bashrc feature.

**Comment by bruhwiler** [comment]
I like the os.environ solution, because it can be put into a Jupyter NB to prevent other users from stumbling onto the problem.

**Comment by robnagler** [comment]
The `~/jupyter/bashrc` addition is on beta.

My $.02: I think the fbpic os.environ change should go in a library, not a notebook. You can't update notebooks, but you can update libraries.

**Comment by bruhwiler** [comment]
Agreed.
