### ISSUE TITLE
Beta release 5/12/2019: fedora 29 and elegant 2019.1.1

### ISSUE THREAD

**Issue by robnagler** [radiasoft/jupyter.radiasoft.org#36]
@cchall would you test beta-jupyter.radiasoft.org to verify that all is well with elegant? The beamsim-jupyter image is based off Fedora 29 now so there may be other incompatible differences. Sirepo tests pass on F29 so it should be fine. Thanks!

**Comment by cchall** [comment]
I tried running a few of my own input files with elegant and SDDS and all appeared to be working fine.
