### ISSUE TITLE
XFEL notebook instructions are out of date

### ISSUE THREAD

**Issue by robnagler** [radiasoft/jupyter.radiasoft.org#38]
The [instructions in the README](https://github.com/radiasoft/jupyter.radiasoft.org#european-xfel-the-wavepropergator-wpg-notebooks-for-running-srw) are not correct, because we are now using JupyterLab, which doesn't open new tabs for terminals (among other things, like button colors have changed).

**Comment by bruhwiler** [comment]
Fixed.

I tried one of the tutorial WPG notebooks and it ran fine.
