### ISSUE TITLE
error importing synergia

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/jupyter.radiasoft.org#4]
​From a Synergia user:

"After the jupyterhub server went down due to disk issues, I found that previously working python notebooks wouldn't work. My guess is those two events are connected and there is some setup step that I need to redo. I've attached a screenshot of the error I encountered."

![error](https://cloud.githubusercontent.com/assets/3825435/24021057/984fe148-0a64-11e7-93b9-d0b72bef9411.png)

**Comment by elventear** [comment]
I think the error is in [`beamsim_jupyter_ipy_kernel_env`](https://github.com/radiasoft/container-beamsim-jupyter/blob/master/container-conf/build.sh#L18), which is not creating the environment variables for the kernel:

```json
{
 "display_name": "Python 2",
 "language": "python",
 "argv": [
  "/home/vagrant/.pyenv/versions/py2/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ]
}
```

**Comment by robnagler** [comment]
Thanks @elventear, I'll take a look.

**Comment by robnagler** [comment]
@jseldred @prebys: This is fixed. Go to the Control Panel then Stop My Server followed by My Server.

The fix was in radiasoft/container-beamsim-jupyter@9393954d691b4888fb18a47d01279dfae0b37007, but the container needed to be pulled.

**Comment by jseldred** [comment]
David created this issue on my behalf, this solved the problem.
