### ISSUE TITLE
Update Pyzgoubi

### ISSUE THREAD

**Issue by bnash** [radiasoft/jupyter.radiasoft.org#49]
We need an updated pyzgoubi in the Docker image for the jupyter server.

**Comment by robnagler** [comment]
I think this is up to date. Let me know if it needs updating again before the workshop.

**Comment by bnash** [comment]
Hi @robnagler , this is not up to date on Jupyter right now.
We need version 0.7.0b1 and we have 0.6.0
Thanks!

**Comment by robnagler** [comment]
Where is 0.7.0b1? It's not on pypi or https://sourceforge.net/projects/pyzgoubi/files/

**Comment by bnash** [comment]
We are able to install it with 
pip install pyzgoubi==0.7.0b1

**Comment by robnagler** [comment]
I see it is specifically marked as a pre-release.

**Comment by bnash** [comment]
Yes, but we would like to have that one installed anyway.  David K. is using features from this in his FFA tutorial.

**Comment by robnagler** [comment]
This will be built when @dtabell's changes to zgoubi are integrated. Probably Thu afternoon. It'll be on alpha/beta then, and we'll push to prod on Fri.

**Comment by bnash** [comment]
Ok, thanks @robnagler .  We can do the pip install ourself, but when using pyzgoubi from Jupyter, David K says that it finds the installed version rather than the newer version, so he wasn't able to use it from Jupyter correctly.

**Comment by robnagler** [comment]
Perhaps he needs to be explicit with `pip2`. pyzgoubi only works with python2. Also, he might have one installed from somewhere else. See commands below for showing which versions.

```sh
jupyter$ pip2 install pyzgoubi==0.7.0b1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pyzgoubi==0.7.0b1
  Downloading https://files.pythonhosted.org/packages/19/3e/637a15d61dc0d378844f26002e9e9719fab4731b9ceeac14daff5933d641/pyzgoubi-0.7.0b1-py2-none-any.whl (129kB)
     |████████████████████████████████| 133kB 2.7MB/s 
Installing collected packages: pyzgoubi
  Found existing installation: pyzgoubi 0.6.0
    Uninstalling pyzgoubi-0.6.0:
      Successfully uninstalled pyzgoubi-0.6.0
Successfully installed pyzgoubi-0.7.0b1
WARNING: You are using pip version 19.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
jupyter$ pyenv which pyzgoubi
/home/vagrant/.pyenv/versions/py2/bin/pyzgoubi
jupyter$ pyzgoubi --version
Pyzgoubi version: 0.7.0b1
Default Zgoubi path zgoubi
Zgoubi, author's dvlpmnt version.
Python version 2.7.16 (default, Jul  3 2019, 16:33:03) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
numpy version 1.16.4
scipy version 1.2.2
matplotlib version 2.2.4
Fedora 29 ( Linux rs6.local 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 )
jupyter$ 
```

**Comment by bnash** [comment]
Thanks, I forwarded your comments to David.

**Comment by robnagler** [comment]
@bnash  pyzgoubi-0.7.0b1 is on beta-jupyter.radiasoft.org. I'll push to prod tomorrow.

**Comment by robnagler** [comment]
See #57 for why I'm pushing to prod now.
