### ISSUE TITLE
Jupyter: Improve appearance of https://jupyter.radiasoft.org/hub/login

### ISSUE THREAD

**Issue by messamer** [radiasoft/jupyter.radiasoft.org#51]
Currently- when a user lands on https://jupyter.radiasoft.org/hub/login they only see Sign In with Github button. We should provide more information about the Jupyter Server and what they can do.
![Screen Shot 2019-08-20 at 12 05 35 PM](https://user-images.githubusercontent.com/29441306/63372191-d88eb600-c342-11e9-8684-360c5fbf8605.png)

**Comment by messamer** [comment]
Related to https://github.com/radiasoft/jupyter.radiasoft.org/issues/35

**Comment by robnagler** [comment]
Here's how to do this: https://pythonforundergradengineers.com/assignments-dir-and-custom-login-page-to-jupyterhub.html

**Comment by bruhwiler** [comment]
Thanks for the info @robnagler -- I am changing the assignment to you, but probably you should delegate.

The previous 'old Sirepo landing page' text is here
https://beta.sirepo.com/old#/jupyter

I think that's good enough for a start.

**Comment by robnagler** [comment]
Mooted by migration to Sirepo login
