### ISSUE TITLE
How would Jupyter extensions work in our setup?

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/jupyter.radiasoft.org#59]
For example, if I wanted to include some of these features:

https://towardsdatascience.com/jupyter-notebook-extensions-517fa69d2231

could I install them and use them? Would extensions get wiped out with updates to the container or anything like that?

That article claims that the extensions only work in Jupyter, but the JupyterLab documentation has information on extensions:

https://jupyterlab.readthedocs.io/en/stable/user/extensions.html

I am demoing Jupyter for science at NAPAC next Tuesday, and before I show people all the extensions they have available, I want to make sure I know how well they play with our environment.

**Comment by robnagler** [comment]
You can't really install extensions dynamically especially with JupyterHub/Docker. They wouldn't persist. We could do some work to making them persist, but it might be tricky.

[You can install extensions](https://github.com/radiasoft/jupyter.radiasoft.org/blob/master/README.md#radia-runsh) before JupyterLab starts in our environment, but this would require some skill.

I would suggest sticking to the extensions that are already installed in our beamsim-jupyter docker image:

* widgetsnbextension
* jupyterlab-manager
* jupyter-matplotlib
* nbzip
* ipywidgets

**Comment by robnagler** [comment]
@sdwebb can I close this?
