### ISSUE TITLE
Adding Puffin to the container

### ISSUE THREAD

**Issue by j-edelen** [radiasoft/jupyter.radiasoft.org#61]
It was requested at the Santa Fe workshop that we include Puffin (a FEL code) in the jupyter container. 

https://github.com/UKFELs/Puffin

**Comment by robnagler** [comment]
I looked at Puffin, and it's a pretty complicated install. They provide a docker image, but that doesn't work for us, of course. How important is this?

**Comment by bruhwiler** [comment]
There are many more GENESIS users than Puffin users.
It would be weird to have Puffin in the container, but not GENESIS.
So I suggest we consider the two codes together.

**Comment by j-edelen** [comment]
Stephen has indicated it would be useful to fastFELO. We should close the loop though. Maybe if we're all at ML next Thursday we can chat about it for 10 min.

**Comment by robnagler** [comment]
@j-edelen I forgot what we decide here. Please let me know what to do about this.

**Comment by j-edelen** [comment]
Stephen had the last action on this to look at which FEL code we were going to support.

**Comment by sdwebb** [comment]
We're going to stick with genesis for now, unless there's a general clamor for puffin.
