### ISSUE TITLE
Error installing parallel Warp on Jupyter server.

### ISSUE THREAD

**Issue by ncook882** [radiasoft/jupyter.radiasoft.org#63]
The following error has been reported when running `make pinstall` with the RadiaSoft-Warp fork on Jupyter. 

> /usr/bin/ld: cannot find -lmpi_usempif08
> /usr/bin/ld: cannot find -lmpi_usempi_ignore_tkr
> /usr/bin/ld: cannot find -lmpi_mpifh
> collect2: error: ld returned 1 exit status
> error: command ‘gcc’ failed with exit status 1
> make[1]: *** [Makefile.Forthon.pympi:20: installso] Error 1

Does the parallel install require new changes to setup.local.py? Currently this is what's specified:

> if parallel:
        library_dirs += ['/usr/lib64/openmpi/lib']
        libraries = fcompiler.libs + ['mpi_usempif08', 'mpi_usempi_ignore_tkr', 'mpi_mpifh', 'mpi']

**Comment by robnagler** [comment]
I think if use use mpicc and mpifort, it'll do the right thing. mpich2 is the mpi implementation.

**Comment by robnagler** [comment]
make FCOMP="-F gfortran --fcompexec mpifort" pclean pinstall

**Comment by ncook882** [comment]
@robnagler I'm running into this error on my own instance. I'm getting the same error:

> /usr/bin/ld: cannot find -lmpi_usempif08
/usr/bin/ld: cannot find -lmpi_usempi_ignore_tkr
/usr/bin/ld: cannot find -lmpi_mpifh
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
make[1]: *** [Makefile.Forthon.pympi:20: installso] Error 1
make[1]: Leaving directory '/home/vagrant/jupyter/radiasoft-warp/warp/pywarp90'
make: *** [Makefile:36: pinstall] Error 2

My Makefile.local.pympi reads:

> FCOMP= -F gfortran --fcompexec mpifort

**Comment by robnagler** [comment]
Is it a clean issue?  Try this:

make FCOMP="-F gfortran --fcompexec mpifort" pclean pinstall

**Comment by robnagler** [comment]
without the Makefile.local.pympi

**Comment by ncook882** [comment]
The suggested command worked for me, but I still had to change the `setup.local.py` file to be:

> if parallel:
     library_dirs += ['/usr/lib64/openmpi/lib']
     libraries = fcompiler.libs + ['mpi']

**Comment by robnagler** [comment]
I built with a fresh clone yesterday, which required no mods to `setup.local.py`. 

openmpi is not installed, but there are a couple of files in `/usr/lib64/openmpi/lib` from boost, but those should be irrelevant to the build. 

`mpifort` should definitely add `mpi` to the list of libraries so that shouldn't be necessary.

Would you run the following commands in a terminal?

```
cd ~/jupyter
export LD_LIBRARY_PATH=/usr/lib64/mpich/lib:/home/vagrant/.local/lib
export PATH=/home/vagrant/.pyenv/bin:/home/vagrant/.local/bin:/home/vagrant/bin:/usr/lib64/mpich/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv global py2
mkdir 20200107
cd 20200107
git clone https://bitbucket.org/radiasoft/warp
cd warp/pywarp90
make FCOMP="-F gfortran --fcompexec mpifort" pclean pinstall
```

If you get an error, copy-and-paste it here with about 50 lines of context.

**Comment by ncook882** [comment]
@robnagler I restarted my server and followed your instructions. Warp installed correctly and I was able to run my test script in parallel.

**Comment by robnagler** [comment]
awesome!
