### ISSUE TITLE
Add jupyter-rs-radia widget

### ISSUE THREAD

**Issue by robnagler** [radiasoft/jupyter.radiasoft.org#66]
[Updated build scripts](https://github.com/radiasoft/container-beamsim-jupyter/commit/2a74a2e1fdb52600a785c22d363dd7b8cf223818)

Building alpha now

**Comment by robnagler** [comment]
@bnash @dtabell This is on beta. [Example5](https://github.com/radiasoft/jupyter-rs-radia/blob/master/examples/RADIA_Example05.ipynb) works for me. Please check it out. If you're satisfied, we can do a production release any time.

In installed this as py3 only.

**Comment by bruhwiler** [comment]
The specified example works for me.

**Comment by sdwebb** [comment]
When I followed that link, I got a 500: Internal Server Error after logging
in with GitHub.

--
Stephen Webb, PhD
Senior Research Scientist
RadiaSoft, LLC
+1 720.502.3928 ext. 705
radiasoft.net - sirepo.com

**Comment by robnagler** [comment]
@sdwebb Would you please try again. The error in the logs may have an intermittent:

```txt
tornado.httpclient.HTTPClientError: HTTP 403: An access token was not returned: The code passed is incorrect or expired.
```
