### ISSUE TITLE
Add genesis to jupyter container

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/jupyter.radiasoft.org#67]
Add Genesis version 3.2.2 beta to the container, this is to support modeling of the TESSA experiment.

**Comment by robnagler** [comment]
Running into some compiling issues. For example:

```txt
src/C++/Util/RandomU.cpp:32:24: error: call of overloaded ‘abs(unsigned int&)’ is ambiguous
```

You can't `abs` an unsigned so it's confusing the compiler. Fixed that, but then I got a missing virtual dtor:

```txt
/usr/bin/ld: readfieldHDF5.cpp:(.text+0x54c): undefined reference to `std::ios_base::Init::~Init()'
```

It probably works in an older gcc version (incorrectly), but we are using 8.x, which is relatively new.

@sdwebb should I spend time on fixing these errors? My choice would be to fix them rather than downgrading the compiler. However, it could be a rat's nest...

**Comment by sdwebb** [comment]
@robnagler sorry I missed this -- see what you can do in a day or two of trying. Past that, downgrade the compiler to get something running. It would also be nice to document these compilation errors so we can share them with Sven, but not necessary.

**Comment by bruhwiler** [comment]
I suggest that @svenreiche should be made aware of the problems now.
He should certainly be made aware of what was done to fix the problems.

**Comment by sdwebb** [comment]
Let's build version 2.0 of Genesis, found here:

http://genesis.web.psi.ch/download/source/genesis_source_2.0_120629.tar.gz

**Comment by robnagler** [comment]
@sdwebb It compiles fine and tells me there's no output. There don't seem to be any input files in the tar ball. Do you have an input file and a sample output?

**Comment by sdwebb** [comment]
@robnagler I do not have test output, but there are sample input files here:

http://genesis.web.psi.ch/inputfiles.html

I have attached the VISA example

[visa.zip](https://github.com/radiasoft/jupyter.radiasoft.org/files/4098973/visa.zip)

**Comment by robnagler** [comment]
Released to beta jupyter server so please try it out. (Note: none of your files are there.)  There are two binaries: genesis and genesis_mpi.

Also the link above didn't work. This is the correct one: http://genesis.web.psi.ch/download/inputfiles/visa.tar

**Comment by sdwebb** [comment]
Aside from the output that this is Version 1.0 when running Genesis, both genesis and genesis_mpi run to completion on beta jupyter with the input files I have. Thanks, Rob!
