### ISSUE TITLE
Shadow on Jupyter server

### ISSUE THREAD

**Issue by bnash** [radiasoft/jupyter.radiasoft.org#73]
Shadow is working on Sirepo now.
I tried it on the RadiaSoft Jupyter server and the module doesn't exist:

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-cefdeec5b2e0> in <module>
      2 import math
      3 import numpy
----> 4 import Shadow
      5 from Shadow.ShadowPreprocessorsXraylib import prerefl, pre_mlayer, bragg
      6 from srxraylib.sources import srfunc

ModuleNotFoundError: No module named 'Shadow'
`

**Comment by robnagler** [comment]
This will be available in the coming days.

**Comment by bnash** [comment]
Any progress here?

**Comment by robnagler** [comment]
I'm working on https://github.com/radiasoft/jupyter-rs-radia/issues/30 which is required for us to release https://github.com/radiasoft/jupyter.radiasoft.org/issues/74.

**Comment by robnagler** [comment]
Done
