### ISSUE TITLE
add GPFlow to container

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/jupyter.radiasoft.org#75]
The container currently contains GPy (https://sheffieldml.github.io/GPy/). GPFlow (https://www.gpflow.org/) has a lot of overlap with GPy, but is built on TensorFlow so they claim it can handle bigger problems and GPFlow seems to have a lot more support. They're both maintained by the same group of people.

@robnagler If it's not much work, could we add GPFlow to the jupyter container? Does anybody have any objections?

**Comment by robnagler** [comment]
It's relatively tiny (1.5MB) so I'll add it. 

Goal would be to get this on prod by tomorrow (see #74).
