### ISSUE TITLE
Switch to HYPRE 2.11.0

### ISSUE THREAD

**Issue by ncook882** [radiasoft/jupyter.radiasoft.org#79]
Our image is currently configured with HYPRE 2.11.2 According to a FLASH developer, most of their developed is done using 2.11.0. Switching back to 2.11.0 may resolve some of the memory issues we are seeing with our 3D FLASH simulations.

**Comment by robnagler** [comment]
Building, which will take a while.

**Comment by robnagler** [comment]
@ncook882 this is on beta. Please try out, and if ok, I'll push to prod tomorrow.

Installed this version: https://github.com/hypre-space/hypre/archive/v2.11.0.tar.gz

**Comment by robnagler** [comment]
FLASH compiles with this.
