### ISSUE TITLE
No module named 'warp' when running from terminal

### ISSUE THREAD

**Issue by ncook882** [radiasoft/jupyter.radiasoft.org#85]
Running Warp scripts, or simply importing Warp, from the terminal results in the following error:

> Traceback (most recent call last):
  File "analytic_witness.py", line 8, in <module>
    from warp import *
ModuleNotFoundError: No module named 'warp'

When running in a notebook, the error does not occur.

**Comment by robnagler** [comment]
What does `pyenv version` say. It should say `py3`

**Comment by ncook882** [comment]
Currently it displays `py2 (set by /home/vagrant/jupyter/.python-version)`

However, if I forcibly use the python 3 or IPython kernels, I still get the same error.

**Comment by robnagler** [comment]
What happens if you:

```sh
pyenv shell py3
python -c 'import warp'
```

**Comment by robnagler** [comment]
And, you want to:

```sh
rm -f /home/vagrant/jupyter/.python-version
```

This will probably fix the problem permanently. You have other `.python-version` files. Find them with:

```sh
find ~/jupyter -name .python-version
```

If you remove them, this will eliminate other issues. It's unlikely you'll be able to use `py2` for anything.

**Comment by ncook882** [comment]
Thanks @robnagler . `pyenv shell py3` fixed my issues.

I also removed my `.python-version` file from my home directory to avoid py2 issues going forward.
